import { AccountAccountCommand } from 'src/commands/account/account';
import { AccountBanksCommand } from 'src/commands/account/account-banks';
import { AccountBookmarksCommand } from 'src/commands/account/account-bookmarks';
import { AccountCardsCommand } from 'src/commands/account/account-cards';
import { AccountChargesCommand } from 'src/commands/account/account-charges';
import { AccountCollectionsCommand } from 'src/commands/account/account-collections';
import { AccountDownloadsCommand } from 'src/commands/account/account-downloads';
import { AccountDraftsCommand } from 'src/commands/account/account-drafts';
import { AccountInvoicesCommand } from 'src/commands/account/account-invoices';
import { AccountLedgersCommand } from 'src/commands/account/account-ledgers';
import { AccountPayoutsCommand } from 'src/commands/account/account-payouts';
import { AccountPlaysCommand } from 'src/commands/account/account-plays';
import { AccountSubscriptionCommand } from 'src/commands/account/account-subscription';
import { AccountTeamsCommand } from 'src/commands/account/account-teams';
import { AccountTransfersCommand } from 'src/commands/account/account-transfers';
import { AccountUsageCommand } from 'src/commands/account/account-usage';

export const AccountCommand = async (action, options: any) => {
	if (action === 'banks') return await AccountBanksCommand(options);
	if (action === 'bookmarks') return await AccountBookmarksCommand(options);
	if (action === 'cards') return await AccountCardsCommand(options);
	if (action === 'charges') return await AccountChargesCommand(options);
	if (action === 'collections') return await AccountCollectionsCommand(options);
	if (action === 'downloads') return await AccountDownloadsCommand(options);
	if (action === 'drafts') return await AccountDraftsCommand(options);
	if (action === 'invoices') return await AccountInvoicesCommand(options);
	if (action === 'ledgers') return await AccountLedgersCommand(options);
	if (action === 'payouts') return await AccountPayoutsCommand(options);
	if (action === 'plays') return await AccountPlaysCommand(options);
	if (action === 'subscription') return await AccountSubscriptionCommand(options);
	if (action === 'teams') return await AccountTeamsCommand(options);
	if (action === 'transfers') return await AccountTransfersCommand(options);
	if (action === 'usage') return await AccountUsageCommand(options);
	return await AccountAccountCommand(options);
};
